
# EL PROBLEMA

Se han desarrollado muchos test estadísticos —tanto paramétricos como no paramétricos — para probar la independencia entre 2 vectores aleatorios, pero dichos test no son aplicables en casos de alta dimensionalidad y de muestras pequeñas.

## Desarrollo teórico

En las situaciones tratadas se consideran *_n_* realizaciones independientes, 


$$
 z_{1} =
\begin{pmatrix} x_1\\
y_1\\
\end{pmatrix} 
 ,  z_{2} =
\begin{pmatrix} x_2\\
y_2\\
\end{pmatrix}, ... ,    z_{n} =
\begin{pmatrix} x_n\\
y_n\\
\end{pmatrix},
$$

de un vector aleatorio continuo 
$$ Z = \mathbf{\begin{pmatrix} X\\
Y\\
\end{pmatrix}},$$
donde  $\mathbf{X}$ $\in$ $\mathcal{X}$ $\subseteq$ $\mathbb{R}^p$  y  $Y$ $\in$ $\mathcal{Y}$ $\subseteq$ $\mathbb{R}^q$




  
## Test existentes
|          *Test paramétricos*          	  |               | *Test no paramétricos*                                                                 	|
|:-----------------------------------:	  |:-------------:|--------------------------------------------------------------------------------------	|
|  Basado en el estadístico Wilk       	  |  *_Univariados_*  |  Estadístico de Spearman $\rho$ y Estadístico de Kendall $\tau$                       	|
|  Prueba de la raíz más grande de Roy   	|               |  Test basado en cuadrantes estadísticos                                               	|
|  Traza de Hotelling-Lawley             	| *_Multivariados_* |  Extensión del test de cuadrantes para mayores dimensiones mediantes interdirecciones 	|
|  Traza de Pillai-Bartlett              	|               |  Generalizaciones multivariadas de los test basados en Spearman y Kendall.            	|
|                                       	|               |  Generalizaciones del cuadrante estadístico usando signos espaciales y rangos         	|

Table: Parangón de los test propuestos hasta el momento.

## test aplicables a HDLSS

Para manipular datos HDLSS en distintas áreas de investigación, se han desarrollado algunos test de independencia entre dos vectores, basados en distancias _inter-point_; sea $d_{x}$ y $d_{y}$ medidas de distancia en $\mathcal{X}$ y $\mathcal{Y}$, respectivamente; y, para toda $(i,j)$, definimos 
$$ d_{ij}^x = d_x(x_i, x_j), \\ d_{ij}^y = d_y(y_i, y_j). $$

En la mayoría de los test presentados, a continuación, se utiliza distancias euclidianas en $\mathcal{X}$ y $\mathcal{Y}$ como  $d_{x}$ y $d_{y}$ , respectivamente.


